### ISSUE TITLE
Allow to specify a default subset of the columns for the writers

### ISSUE THREAD

**Issue by Avsecz** [kipoi/models#125]
In `model.yaml`, add the following entry:

```yaml
writers:
  tsv:
    rename_subset_columns:
       new_colname: metadata/...
       new_colname: metadata/...
       predictions: preds
```

Additionally, we would need to add a CLI flag to `kipoi predict` to keep the default writer configuration. e.g. `kipoi predict `--default-writers`

## Tasks

- [ ] add new field to ModelDescription https://github.com/kipoi/kipoi/blob/master/kipoi/specs.py#L780-L796
   - `writers = related.ChildField(Writers)`

```python
class Writers(RelatedConfigMixin):
    tsv = related.ChildField(TsvWriterSpec)

class TsvWriterSpec(RelatedConfigMixin):
    rename_subset_columns = related.ChildField(dict, required=False)
```

- [ ] implement this re-naming feature within the writer itself e.g. add new arguments to `TsvBatchWriter`. 
- [ ] add `--default-writers` to `kipoi predict` 

Any other suggestion improvements of how to structure or name things @s6juncheng ?

**Comment by Avsecz** [comment]
I think this functionality specifically can be solved by writing a custom parser of the output.tsv file.
