### ISSUE TITLE
Add Basenji

### ISSUE THREAD

**Issue by Avsecz** [kipoi/models#26]
Repo: https://github.com/calico/basenji

### Model
type: tensorflow
Get model weights: 

```bash
wget https://storage.googleapis.com/131k/model.tf.index
wget https://storage.googleapis.com/131k/model.tf.meta
wget https://storage.googleapis.com/131k/model.tf.data-00000-of-00001
```

### Dataloader

- Simple fasta + bed dataloader as for deepsea

### Dimensions

- TODO

### TODO's

- [x] try to run the model
- [x] write out the dimensions
- [x] add tensorflow to Kipoi
- [ ] PR
